#!/usr/bin/env python3
"""
Generates src/layouts/browser/browser-positions.generated.xml

Single source for the browser <pos> tables. VirtualDJ selects a rung by
condition; it cannot compute var-dependent geometry inline (a get_var/backtick
term in an x/y/width/height *value* is dropped — only conditions read vars), so
each surface must enumerate one rung per state:
  - 14 waveform sizes: @$infntywavesize 0-13 (step = 20px), and optionally
  - 8 rack combinations: any subset of fx (80px), mixer (86px), video (140px).

Each surface in SURFACES supplies its own x/width and y/height templates (so the
performance, pro, and pro-4deck formulas stay exact) plus whether it iterates the
rack combos. Templates use:
  {wave}  = 7 + 20*n    (per-wavesize y offset; 7 at n=0, 267 at n=13)
  {hbase} = 121 + 20*n  (per-wavesize height term; 121 at n=0, 381 at n=13)
  {yr} {hr} = rack y/height terms from RACK_COMBOS ("" for wave-only surfaces)

VirtualDJ evaluates <pos> elements in order and applies the first whose condition
matches, so rack combos are listed most-specific-first (3 racks -> 2 -> 1 -> 0).

Do not edit the generated file — edit this script instead.
"""

import sys
from pathlib import Path

OUTPUT = Path(__file__).parent.parent / "src/layouts/browser/browser-positions.generated.xml"

# Rack combos ordered most-specific-first.
# Each entry: (rack_condition_prefix, y_rack_terms, h_rack_terms)
# Conditions use VDJ's `?` as AND; first match wins at runtime.
RACK_COMBOS = [
    (
        "var_equal '@$show_fx_rack' 1 ? var_equal '@$show_mixer_rack' 1 ? var_equal '@$show_video_rack' 1",
        "+80+2+86+2+140+2",
        "-80-2-86-2-140-2",
    ),
    (
        "var_equal '@$show_mixer_rack' 1 ? var_equal '@$show_video_rack' 1",
        "+86+2+140+2",
        "-86-2-140-2",
    ),
    (
        "var_equal '@$show_fx_rack' 1 ? var_equal '@$show_video_rack' 1",
        "+80+2+140+2",
        "-80-2-140-2",
    ),
    (
        "var_equal '@$show_mixer_rack' 1 ? var_equal '@$show_fx_rack' 1",
        "+80+2+86+2",
        "-80-2-86-2",
    ),
    (
        "var_equal '@$show_video_rack' 1",
        "+140+2",
        "-140-2",
    ),
    (
        "var_equal '@$show_mixer_rack' 1",
        "+86+2",
        "-86-2",
    ),
    (
        "var_equal '@$show_fx_rack' 1",
        "+80+2",
        "-80-2",
    ),
    (
        "",  # no racks active
        "",
        "",
    ),
]

# A wave-only surface makes a single pass with no rack condition or offsets.
NO_RACKS = [("", "", "")]

SURFACES = [
    # Performance / Pro-extended / Pro-mixer-2deck: rack-aware (8 combos x 14 sizes).
    dict(
        cls="BROWSER_PERFORMANCE_SURFACE",
        placeholders="*height,bottom_trim=0",
        racks=RACK_COMBOS,
        x="+0",
        width="1920",
        y="+[HEIGHT]+{wave}-432{yr}-66+50-10-12-18",
        h="+[HEIGHT]-{hbase}{hr}-[BOTTOM_TRIM]",
    ),
    # Pro 2-deck (wave-only).
    dict(
        cls="BROWSER_SURFACE_PRO",
        placeholders="*height",
        racks=NO_RACKS,
        x="0",
        width="1920",
        y="1080-[HEIGHT]+{wave}-207",
        h="+[HEIGHT]-{wave}+207-50",
    ),
    # Pro 4-deck (wave-only).
    dict(
        cls="BROWSER_SURFACE_PRO_4DECKS",
        placeholders="*height",
        racks=NO_RACKS,
        x="+2",
        width="1920-4",
        y="+[HEIGHT]+{wave}+432+4-200+38",
        h="[HEIGHT]-{hbase}",
    ),
]


def pos_elements(surface):
    """Yield the <pos> lines for one surface (rack combos x 14 wavesizes)."""
    for rack_cond, y_rack, h_rack in surface["racks"]:
        for n in range(13, -1, -1):
            wave = 7 + n * 20       # 7 at n=0, 267 at n=13
            hbase = 121 + n * 20    # 121 at n=0, 381 at n=13

            y = surface["y"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)
            h = surface["h"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)

            if rack_cond:
                condition = f"{rack_cond} ? var_equal '@$infntywavesize' {n}"
            else:
                condition = f"var_equal '@$infntywavesize' {n}"

            yield (
                f'    <pos x="{surface["x"]}" y="{y}" width="{surface["width"]}"'
                f' height="{h}" condition="{condition}"/>'
            )


def generate():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->",
        "<defs>",
    ]

    for surface in SURFACES:
        lines.append(f'  <define class="{surface["cls"]}" placeholders="{surface["placeholders"]}">')
        lines.append('    <browser class="browser_ui_base">')
        lines.extend(pos_elements(surface))
        lines.append("    </browser>")
        lines.append("  </define>")

    lines.append("</defs>")
    return "\n".join(lines) + "\n"


def main(argv):
    content = generate()
    if argv == ["--check"]:
        if not OUTPUT.exists():
            print(f"Missing {OUTPUT}")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(f"Out of date {OUTPUT}; run `just generate`")
            return 1
        print(f"Verified {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
        return 0
    if argv:
        print("Usage: gen-browser-positions.py [--check]", file=sys.stderr)
        return 2
    if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == content:
        print(f"Unchanged {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Written {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
