#!/usr/bin/env python3
"""
Generates coupled browser position tables and the waveform height ladder.

Single source for the browser <pos> tables. VirtualDJ selects a rung by
condition; it cannot compute var-dependent geometry inline (a get_var/backtick
term in an x/y/width/height *value* is dropped — only conditions read vars), so
each surface must enumerate one rung per state:
  - 14 waveform sizes: @$dd_wave_size 0-13 (step = 20px), and optionally
  - 8 rack combinations: any subset of fx (80px), mixer (86px), video (140px).

Each surface in SURFACES supplies its own x/width and y/height templates (so the
performance, pro, and pro-4deck formulas stay exact) plus whether it iterates the
rack combos. Templates use:
  {wave}  = 7 + 20*n    (per-wavesize y offset; 7 at n=0, 267 at n=13)
  {hbase} = 121 + 20*n  (per-wavesize height term; 121 at n=0, 381 at n=13)
  {yr} {hr} = rack y/height terms from RACK_COMBOS ("" for wave-only surfaces)

VirtualDJ evaluates <pos> elements in order and applies the first whose condition
matches, so rack combos are listed most-specific-first (3 racks -> 2 -> 1 -> 0).

Do not edit the generated file — edit this script instead.
"""

import sys
from pathlib import Path

from skin_geometry import rack_combinations, wave_sizes

OUTPUT = Path(__file__).parent.parent / "src/layouts/browser/browser-positions.generated.xml"

# Shared dimensions also drive the Stack browser and waveform ladder.
RACK_COMBOS = list(rack_combinations())

# A wave-only surface makes a single pass with no rack condition or offsets.
NO_RACKS = [("", "", "")]

SURFACES = [
    # Performance / Pro-extended / Pro-mixer-2deck: rack-aware (8 combos x 14 sizes).
    dict(
        cls="BROWSER_PERFORMANCE_SURFACE",
        placeholders="*height,bottom_trim=0",
        racks=RACK_COMBOS,
        x="+0",
        width="1920",
        y="+[HEIGHT]+{wave}-432{yr}-66+50-10-12-18",
        h="+[HEIGHT]-{hbase}{hr}-[BOTTOM_TRIM]",
    ),
    # Pro 2-deck (wave-only).
    dict(
        cls="BROWSER_SURFACE_PRO",
        placeholders="*height",
        racks=NO_RACKS,
        x="0",
        width="1920",
        y="1080-[HEIGHT]+{wave}-207",
        h="+[HEIGHT]-{wave}+207-50",
    ),
]


def pos_elements(surface):
    """Yield the <pos> lines for one surface (rack combos x 14 wavesizes)."""
    for rack_cond, y_rack, h_rack in surface["racks"]:
        for n, wave, hbase in wave_sizes():

            y = surface["y"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)
            h = surface["h"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)

            if rack_cond:
                condition = f"{rack_cond} ? var_equal '@$dd_wave_size' {n}"
            else:
                condition = f"var_equal '@$dd_wave_size' {n}"

            yield (
                f'    <pos x="{surface["x"]}" y="{y}" width="{surface["width"]}"'
                f' height="{h}" condition="{condition}"/>'
            )


def generate():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->",
        "<defs>",
    ]

    for surface in SURFACES:
        lines.append(f'  <define class="{surface["cls"]}" placeholders="{surface["placeholders"]}">')
        lines.append('    <browser class="browser_ui_base">')
        lines.extend(pos_elements(surface))
        lines.append("    </browser>")
        lines.append("  </define>")

    lines.append("</defs>")
    return "\n".join(lines) + "\n"


def generate_stack():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
    ]
    for cls, base in (
        ("BROWSER_SURFACE_STACK", "+[HEIGHT]+7-200-164-3-164+38"),
        ("BROWSER_SURFACE_STACK_4DECKS", "+[HEIGHT]+7-200+2+164+2+164+38+1"),
    ):
        lines.append(f'  <define class="{cls}" placeholders="*height">')
        lines.append('    <browser class="browser_ui_base">')
        for condition, added, removed in rack_combinations(stack=True):
            check = f' condition="{condition}"' if condition else ""
            lines.append(f'      <pos y="{base}{added}" width="1920" height="+[HEIGHT]{removed}"{check}/>')
        lines.extend(['    </browser>', '  </define>'])
    lines.append('</defs>')
    return "\n".join(lines) + "\n"


def generate_waveforms():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
        '  <define class="AREA_WAVES">',
    ]
    for state, _, height in wave_sizes():
        lines.append(
            f'    <panel class="waveform" x="+2" waveformheight="{height}"'
            f' condition="var_equal \'@$dd_wave_size\' {state}"/>')
    lines.extend(['  </define>', '</defs>'])
    return "\n".join(lines) + "\n"


def generated_files():
    src = Path(__file__).resolve().parent.parent / "src"
    return {
        OUTPUT: generate(),
        src / "layouts/browser/browser-stack-positions.generated.xml": generate_stack(),
        src / "components/waveforms/waveform-sizes.generated.xml": generate_waveforms(),
    }


def main(argv):
    if argv not in ([], ["--check"]):
        print("Usage: gen-browser-positions.py [--check]", file=sys.stderr)
        return 2
    failed = False
    for path, content in generated_files().items():
        matches = path.exists() and path.read_text(encoding="utf-8") == content
        if argv == ["--check"]:
            if not matches:
                print(f"Missing or out of date {path}; run `just generate`")
                failed = True
            else:
                print(f"Verified {path}")
        elif matches:
            print(f"Unchanged {path}")
        else:
            path.write_text(content, encoding="utf-8")
            print(f"Written {path}")
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
