#!/usr/bin/env python3
"""
Generates coupled browser position tables, the waveform height ladder, the
rack toggle component (with its browser-fit guards) and the LED VU meters.

Single source for the browser <pos> tables. VirtualDJ selects a rung by
condition; it cannot compute var-dependent geometry inline (a get_var/backtick
term in an x/y/width/height *value* is dropped — only conditions read vars), so
each surface must enumerate one rung per state:
  - 14 waveform sizes: @$dd_wave_size 0-13 (step = 20px), and optionally
  - 8 rack combinations: any subset of fx (80px), mixer (86px), video (140px).

Each surface in SURFACES supplies its own x/width and y/height templates (so the
performance, pro, and pro-4deck formulas stay exact) plus whether it iterates the
rack combos. Templates use:
  {wave}  = 7 + 20*n    (per-wavesize y offset; 7 at n=0, 267 at n=13)
  {hbase} = 121 + 20*n  (per-wavesize height term; 121 at n=0, 381 at n=13)
  {yr} {hr} = rack y/height terms from RACK_COMBOS ("" for wave-only surfaces)

VirtualDJ evaluates <pos> elements in order and applies the first whose condition
matches, so rack combos are listed most-specific-first (3 racks -> 2 -> 1 -> 0).

Do not edit the generated file — edit this script instead.
"""

import sys
from pathlib import Path

from skin_geometry import (BROWSER_MIN_HEIGHT, LED_HEIGHT, LED_PITCH, RACK_HEIGHTS, VU_METERS,
                           rack_combinations, rack_fit_script, vu_meter_height, wave_sizes)

OUTPUT = Path(__file__).parent.parent / "src/layouts/browser/browser-positions.generated.xml"

# Shared dimensions also drive the Stack browser and waveform ladder.
RACK_COMBOS = list(rack_combinations())

# A wave-only surface makes a single pass with no rack condition or offsets.
NO_RACKS = [("", "", "")]

SURFACES = [
    # Performance / Pro-extended / Pro-mixer-2deck: rack-aware (8 combos x 14 sizes).
    dict(
        cls="BROWSER_PERFORMANCE_SURFACE",
        placeholders="*height,bottom_trim=0",
        racks=RACK_COMBOS,
        x="+0",
        width="1920",
        y="+[HEIGHT]+{wave}-432{yr}-66+50-10-12-18",
        h="+[HEIGHT]-{hbase}{hr}-[BOTTOM_TRIM]",
    ),
    # Pro 2-deck (wave-only).
    dict(
        cls="BROWSER_SURFACE_PRO",
        placeholders="*height",
        racks=NO_RACKS,
        x="0",
        width="1920",
        y="1080-[HEIGHT]+{wave}-207",
        h="+[HEIGHT]-{wave}+207-50",
    ),
]


def pos_elements(surface):
    """Yield the <pos> lines for one surface (rack combos x 14 wavesizes)."""
    for rack_cond, y_rack, h_rack in surface["racks"]:
        for n, wave, hbase in wave_sizes():

            y = surface["y"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)
            h = surface["h"].format(wave=wave, hbase=hbase, yr=y_rack, hr=h_rack)

            if rack_cond:
                condition = f"{rack_cond} ? var_equal '@$dd_wave_size' {n}"
            else:
                condition = f"var_equal '@$dd_wave_size' {n}"

            yield (
                f'    <pos x="{surface["x"]}" y="{y}" width="{surface["width"]}"'
                f' height="{h}" condition="{condition}"/>'
            )


def generate():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->",
        "<defs>",
    ]

    for surface in SURFACES:
        lines.append(f'  <define class="{surface["cls"]}" placeholders="{surface["placeholders"]}">')
        lines.append('    <browser class="browser_ui_base">')
        lines.extend(pos_elements(surface))
        lines.append("    </browser>")
        lines.append("  </define>")

    lines.append("</defs>")
    return "\n".join(lines) + "\n"


def generate_stack():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
    ]
    for cls, base in (
        ("BROWSER_SURFACE_STACK", "+[HEIGHT]+7-200-164-3-164+38"),
        ("BROWSER_SURFACE_STACK_4DECKS", "+[HEIGHT]+7-200+2+164+2+164+38+1"),
    ):
        lines.append(f'  <define class="{cls}" placeholders="*height">')
        lines.append('    <browser class="browser_ui_base">')
        for condition, added, removed in rack_combinations(stack=True):
            check = f' condition="{condition}"' if condition else ""
            lines.append(f'      <pos y="{base}{added}" width="1920" height="+[HEIGHT]{removed}"{check}/>')
        lines.extend(['    </browser>', '  </define>'])
    lines.append('</defs>')
    return "\n".join(lines) + "\n"


def generate_waveforms():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
        '  <define class="AREA_WAVES">',
    ]
    for state, _, height in wave_sizes():
        lines.append(
            f'    <panel class="waveform" x="+2" waveformheight="{height}"'
            f' condition="var_equal \'@$dd_wave_size\' {state}"/>')
    lines.extend(['  </define>', '</defs>'])
    return "\n".join(lines) + "\n"


RACK_LABELS = {"mixer": "MIXER", "video": "VIDEO", "fx": "EFFECTS"}
RACK_TOOLTIPS = {"mixer": "Show/Hide Mixer Rack", "video": "Show/Hide Video Rack", "fx": "Show/Hide Effects Rack"}


def rack_toggle_action(rack):
    """Hide when shown; otherwise show only if the browser keeps its minimum height."""
    var = f"'@$dd_show_{rack}_rack'"
    others = " & ".join(f"set '@$dd_show_{other}_rack' 0" for other in RACK_HEIGHTS if other != rack)
    show_single = f"set {var} 1 & {others} & load_skin"
    show_multi = f"set {var} 1 & load_skin"
    return (f"var_equal {var} 1 ? set {var} 0 & load_skin : "
            f"var_equal '@$dd_rack_mode' 1 ? {rack_fit_script(rack, single=True, yes=show_single, no='nothing')} : "
            f"{rack_fit_script(rack, single=False, yes=show_multi, no='nothing')}")


def rack_toggle_enabled(rack, negate=False):
    var = f"'@$dd_show_{rack}_rack'"
    yes, no = ("false", "true") if negate else ("true", "false")
    return (f"var_equal {var} 1 ? {yes} : var_equal '@$dd_rack_mode' 1 ? "
            f"{rack_fit_script(rack, single=True, yes=yes, no=no)} : {rack_fit_script(rack, single=False, yes=yes, no=no)}")


def xml_attr(value):
    return value.replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")


def generate_rack_toggles():
    """One rack toggle design for every mode; callers pass placement and palette."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
        f'  <!-- Shared rack toggles. A rack can be shown only while the browser keeps at least',
        f'       {BROWSER_MIN_HEIGHT}px (scripts/skin_geometry.py); otherwise the button renders dimmed and inert.',
        '       Pro/Performance add the RACKS frame; Stack places the same buttons unframed next to PADS. -->',
        '  <define class="TOPBAR_RACK_TOGGLES" placeholders="inset_x=+5,inset_y=+9,x_mixer=+0,x_video=+60,x_fx=+60*2,'
        'width=55,width_fx=65,coloroff=black,coloron=#222222,colorover=#000000,colordown=#222222,'
        'colorselected=#333333,textcolor=textoff,textcolorover=white,textcoloron=white,textcolordisabled=#444444,*frame=true">',
        '    <group>',
        '      <group x="[INSET_X]" y="[INSET_Y]">',
        '        <!-- dimmed, inert buttons: shown while the rack is off and would not fit -->',
        '        <group>',
    ]
    for rack in ("mixer", "video", "fx"):
        width = "[WIDTH_FX]" if rack == "fx" else "[WIDTH]"
        lines += [
            f'          <button class="button_main" x="[X_{rack.upper()}]" width="{width}" height="27" bordersize="0" action="nothing" query="off"'
            f' tooltip="{RACK_TOOLTIPS[rack]}\\nNot enough room for the browser at this wave size" visibility="{xml_attr(rack_toggle_enabled(rack, negate=True))}">',
            '            <off color="[COLOROFF]"/>',
            f'            <text color="[TEXTCOLORDISABLED]" size="12" text="{RACK_LABELS[rack]}"/>',
            '          </button>',
        ]
    lines += ['        </group>', '        <!-- live toggles -->', '        <group>']
    for rack in ("mixer", "video", "fx"):
        width = "[WIDTH_FX]" if rack == "fx" else "[WIDTH]"
        lines += [
            f'          <button class="button_main" x="[X_{rack.upper()}]" width="{width}" height="27" bordersize="0" tooltip="{RACK_TOOLTIPS[rack]}"'
            f' query="var \'@$dd_show_{rack}_rack\'" action="{xml_attr(rack_toggle_action(rack))}" visibility="{xml_attr(rack_toggle_enabled(rack))}">',
            '            <off color="[COLOROFF]"/>',
            '            <on color="[COLORON]"/>',
            '            <over color="[COLOROVER]"/>',
            '            <down color="[COLORDOWN]"/>',
            '            <selected color="[COLORSELECTED]"/>',
            f'            <text color="[TEXTCOLOR]" colorover="[TEXTCOLOROVER]" size="12" coloron="[TEXTCOLORON]" text="{RACK_LABELS[rack]}"/>',
            '          </button>',
        ]
    lines += [
        '        </group>',
        '      </group>',
        "      <group condition=\"param_equal '[FRAME]' 'true'\">",
        '        <!-- border -->',
        '        <visual x="+0" y="+8" width="190" height="28">',
        '          <off shape="square" color="transparent" border_size="1" border="#333333" radius="6"/>',
        '        </visual>',
        '        <!-- label -->',
        '        <textzone x="+0">',
        '          <size width="180" height="16"/>',
        '          <text fontsize="9" weight="normal" color="#999999" align="center" text="RACKS" important="true"/>',
        '        </textzone>',
        '      </group>',
        '    </group>',
        '  </define>',
        '</defs>',
    ]
    return "\n".join(lines) + "\n"


def generate_vu_meters():
    """LED VU ladders: deck-colored by default, green/orange/red with @$dd_vu_alt_colors."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/gen-browser-positions.py — do not edit directly -->',
        '<defs>',
        '  <!-- LED-style VU meter variants (counts in scripts/skin_geometry.py VU_METERS) -->',
    ]
    def led(y, color):
        return [
            f'      <led x="+0" y="{y}" width="11" height="{LED_HEIGHT}">',
            '        <off color="[VUCOLOROFF]" radius="0" border="contrast" border_size="0"/>',
            f'        <on color="{color}" radius="0" border="contrast" border_size="0"/>',
            '      </led>',
        ]
    for cls, spec in VU_METERS.items():
        height = vu_meter_height(spec["leds"])
        lines.append(f'  <define class="{cls}" placeholders="*source,peak,showpeaks,width=11,height={LED_HEIGHT},vucoloroff=vu_background">')
        for alt in (0, 1):
            lines.append(f'    <visual type="vumeter" width="11" height="{height}" source="[SOURCE]" smooth="no"'
                         f' visibility="var_equal \'@$dd_vu_alt_colors\' {alt}">')
            for index in range(spec["leds"] - 1, -1, -1):
                y = "+0" if index == 0 else f"+{LED_PITCH}*{index}"
                if alt:
                    color = "red_vu" if index < spec["red"] else "orange_vu" if index < spec["red"] + spec["orange"] else "green_vu"
                else:
                    color = "needle" if index < spec["needle"] else "deckcolor"
                lines += led(y, color)
            lines.append('    </visual>')
        lines += [
            '    <slider action="[SOURCE]_peak" orientation="vertical" direction="up" smooth="no"'
            ' visibility="[SHOWPEAKS] ? [SOURCE]_peak &amp; param_bigger 0">',
            f'      <pos x="+0" y="+0" width="11" height="{height}"/>',
            '      <fader>',
            f'        <size width="11" height="{LED_HEIGHT}"/>',
            '        <off shape="square" color="needle" radius="0" border="black" border_size="0"/>',
            '      </fader>',
            '    </slider>',
            '  </define>',
        ]
    lines.append('</defs>')
    return "\n".join(lines) + "\n"


def generated_files():
    src = Path(__file__).resolve().parent.parent / "src"
    return {
        OUTPUT: generate(),
        src / "layouts/browser/browser-stack-positions.generated.xml": generate_stack(),
        src / "components/waveforms/waveform-sizes.generated.xml": generate_waveforms(),
        src / "components/topbar/rack-toggles.generated.xml": generate_rack_toggles(),
        src / "components/meters.generated.xml": generate_vu_meters(),
    }


def main(argv):
    if argv not in ([], ["--check"]):
        print("Usage: gen-browser-positions.py [--check]", file=sys.stderr)
        return 2
    failed = False
    for path, content in generated_files().items():
        matches = path.exists() and path.read_text(encoding="utf-8") == content
        if argv == ["--check"]:
            if not matches:
                print(f"Missing or out of date {path}; run `just generate`")
                failed = True
            else:
                print(f"Verified {path}")
        elif matches:
            print(f"Unchanged {path}")
        else:
            path.write_text(content, encoding="utf-8")
            print(f"Written {path}")
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
